#!/usr/bin/env bash
# ============================================================
#  Vantage - apply CHK-03 security headers via Nginx
#  Sahil Bawa, Murdoch ICT171, 2026 S1
#
#  Run this once on the droplet (as root):
#    sudo bash harden_headers.sh
#
#  What it does:
#    1. Writes /etc/nginx/snippets/vantage-security-headers.conf
#       with the 5 security headers CHK-03 looks for.
#    2. Patches /etc/nginx/sites-available/default to include
#       that snippet inside the vantageproject.me server block.
#    3. Validates the config with `nginx -t`.
#    4. If valid, reloads Nginx. If invalid, restores the backup.
#    5. Reruns vantage_check.sh and prints CHK-03's new state.
#
#  Idempotent: safe to run more than once.
# ============================================================

set -e

SNIPPET="/etc/nginx/snippets/vantage-security-headers.conf"
CONF="/etc/nginx/sites-available/default"
BACKUP="$CONF.bak-$(date +%Y%m%d-%H%M%S)"
CHECK_SCRIPT="/usr/local/bin/vantage_check.sh"
STATUS_FILE="/var/www/html/admin/status.json"

# --- Step 1: write the snippet ----------------------------------------------
echo "==> Writing security headers snippet to $SNIPPET"
mkdir -p /etc/nginx/snippets
cat > "$SNIPPET" <<'EOF'
# Vantage security headers — included from the HTTPS server block.
# Generated by harden_headers.sh.
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
add_header X-Frame-Options           "DENY" always;
add_header X-Content-Type-Options    "nosniff" always;
add_header Referrer-Policy           "strict-origin-when-cross-origin" always;
add_header Content-Security-Policy   "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none';" always;
EOF
chmod 644 "$SNIPPET"

# --- Step 2: patch the main config (only if not already patched) ------------
if grep -q "vantage-security-headers.conf" "$CONF"; then
  echo "==> Include directive already present in $CONF — no patch needed."
else
  echo "==> Backing up $CONF to $BACKUP"
  cp "$CONF" "$BACKUP"

  echo "==> Adding include directive after 'server_name vantageproject.me;'"
  sed -i '/server_name vantageproject\.me;/a\    include /etc/nginx/snippets/vantage-security-headers.conf;' "$CONF"

  # Verify the patch actually landed
  if ! grep -q "vantage-security-headers.conf" "$CONF"; then
    echo "!! sed did not match 'server_name vantageproject.me;' in $CONF."
    echo "   Config is unchanged. Inspect $CONF and re-run, or add the include line by hand."
    exit 1
  fi
fi

# --- Step 3: validate -------------------------------------------------------
echo "==> Running 'nginx -t' to validate the config"
if ! nginx -t; then
  echo ""
  echo "!! nginx -t FAILED. Rolling back to $BACKUP."
  if [ -f "$BACKUP" ]; then
    cp "$BACKUP" "$CONF"
    echo "   $CONF restored from backup."
    echo "   The snippet at $SNIPPET is kept for inspection but is no longer referenced."
  fi
  exit 1
fi

# --- Step 4: reload Nginx ---------------------------------------------------
echo "==> Reloading Nginx"
systemctl reload nginx

# --- Step 5: spot-check headers from outside -------------------------------
echo ""
echo "==> Headers now being served on https://vantageproject.me/ :"
curl -sI https://vantageproject.me/ | grep -iE 'strict-transport|x-frame|x-content-type|referrer-policy|content-security' || \
  echo "   (no security headers found — something's wrong)"

# --- Step 6: rerun the check script + report CHK-03 ------------------------
echo ""
if [ -x "$CHECK_SCRIPT" ]; then
  echo "==> Rerunning $CHECK_SCRIPT"
  "$CHECK_SCRIPT"

  echo ""
  echo "==> CHK-03 result from $STATUS_FILE:"
  python3 - <<PYEOF
import json, sys
try:
    d = json.load(open("$STATUS_FILE"))
    chk = next((c for c in d.get("checks", []) if c.get("id") == "CHK-03"), None)
    if chk:
        print("   status:  ", chk.get("status"))
        print("   grade:   ", chk.get("grade"))
        print("   detail:  ", chk.get("detail"))
    else:
        print("   (CHK-03 not found in status.json)")
except Exception as e:
    print("   could not parse status.json:", e)
    sys.exit(1)
PYEOF
else
  echo "==> $CHECK_SCRIPT not found. Skipping rerun."
  echo "   Run it manually once the check script is in place."
fi

echo ""
echo "Done."
echo ""
echo "If CHK-03 now reports grade A with 'All recommended headers present.', the fix is live."
echo "If anything looks wrong, the previous Nginx config is at: $BACKUP"
